### ISSUE TITLE
is that any possible way to get the State (Charging,Disconnect,Connected)  and the Other configuration Values(Max Power ,Min Power) Parrallely?

### ISSUE THREAD

**Issue by qasimali-byte** [SmartEVSE/SmartEVSE-2#17]
Hi @wido @bobosch @Links2004 @mstegen @maximevince  I am Working on the Smart EVSE. I Connected the EVSE with Compute Module 3+ over the USART, and I am able to get the Values from the Terminal and set the EVSE Configuration Values through the terminal. actually, my concern to get the STATE info and the other configuration parallelly from the EVSE, as per my understanding about EVSE  respond only one Command at a time. so is that any other way to get the STATE from the EVSE parallel to the Configuration.

**Comment by bobosch** [comment]
https://github.com/SmartEVSE/SmartEVSE-2/issues/12#issuecomment-839608368
