### ISSUE TITLE
Setting LOG_DEBUG from menu?

### ISSUE THREAD

**Issue by fluppie** [SmartEVSE/SmartEVSE-2#20]
Is is possible to set this from the menu?
```
#define LOG_EVSE LOG_DEBUG                                                       // Default: LOG_INFO
#define LOG_MODBUS LOG_DEBUG                                                // Default: LOG_WARN
```

Or only through re-compiling in MP Lab X and flashing the modified FW?

**Comment by mstegen** [comment]
The debug options are only available as a compile time option. It's not possible to set them from the menu.
