### ISSUE TITLE
EVSE V3 Set Access bit

### ISSUE THREAD

**Issue by TonKro** [SmartEVSE/SmartEVSE-2#56]
I am trying to set the access bit via a serial port. Looks like I am doing something wrong?

Example for Node 3:

Node 3 = 0x4
Access register = 0xA7

Sending for Access:
4,6,0,A7,0,1 + CRC

Sending for No Access

4,6,0,A7,0,0 + CRC

Hope someone can give me some help.

**Comment by bobosch** [comment]
Which version do you use? After 2.20 the modbus register had changed (0x0005 instead of 0x00a7)
https://github.com/SmartEVSE/SmartEVSE-2#register-0x00-evse-status

**Comment by TonKro** [comment]
Thank you so much, this was indeed the issue. Working with later version then 2.20...
